services:

  mongo:
    container_name: mongo-database-container
    image: mongo
    volumes:
      - mongovolume:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_LOGIN
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD

  server:
    container_name: server-container
    build: ./server
    ports:
      - $SERVER_EXTERNAL_PORT:$SERVER_INTERNAL_PORT
    environment:
      - SERVER_INTERNAL_PORT=$SERVER_INTERNAL_PORT
      - SERVER_EXTERNAL_PORT=$SERVER_EXTERNAL_PORT
      - MONGODB_SERVICE_NAME=$MONGODB_SERVICE_NAME
      - MONGODB_INTERNAL_PORT=$MONGODB_INTERNAL_PORT
      - MONGODB_LOGIN=$MONGODB_LOGIN
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$DB_NAME
      - CLIENT_EXTERNAL_PORT=$CLIENT_EXTERNAL_PORT
    depends_on:
      - mongo

  client:
    container_name: client-container
    build: ./client
    ports:
      - $CLIENT_EXTERNAL_PORT:$CLIENT_INTERNAL_PORT
    environment:
      - NUXT_ENV_API_BASE_URL=$NUXT_ENV_API_BASE_URL
    depends_on:
      - mongo
      - server

volumes:
  mongovolume: